### ISSUE TITLE
Request for Comment: Do we need man, epub, single page?

### ISSUE THREAD

**Issue by ryantm** [ryantm/mmdoc#15]
In the name of simplifying this tool, I'm thinking about removing support for single page, epub, and man pages, and focusing solely on the multipage output. Anyone have some strong objection to this? I'd leave a branch that has those around, so we could refer to it if we wanted to add them back later.

Notes:
* epub only barely works and I bet it will take a lot of work to get working right, it also adds dependencies like libzip
* Man pages barely make sense as they are currently implemented. The main problem is how to name them. I guess it could make sense to generate a single man page like the single page output.
* Single page is probably the easiest to maintain but, still nicer to just focus on one output.

**Comment by samueldr** [comment]
epub people will request it. I guess it only makes sense if it's not prohibitive to maintain though.

Single-page man is probably the way to go. Maybe some way to manually split?

Relatedly, single-page output we'd need the same. E.g. to split the appendices into their own pages. Might be helpful to also offload other big pages off of the main single-page output.
