### ISSUE TITLE
Overlapping text in the generated manual page for stdenv

### ISSUE THREAD

**Issue by anka-213** [ryantm/mmdoc#31]
I'm not exactly sure what causes it, but on this page https://ryantm.github.io/nixpkgs/stdenv/stdenv/, the bottom of the page spilled out of the `<div class="body"><section id="main"><main>...` block and is instead directly in the `<body>` which makes it into an overlapping mess, with the last part of the page in the background and unscrollable.

<img width="1297" alt="Screenshot 2022-10-29 at 19 50 51" src="https://user-images.githubusercontent.com/475451/198846016-fb9797d6-6af1-4276-8f06-bb183f7922da.png">

Looking at the generated html code, it looks like there was a spurious `</div>` generated, which triggers the behaviour (at least in google chrome):

```html
...
<p>Use <code>--prefix</code> to explicitly set dependencies in <code>PATH</code>.</p>
<p>
<code>--prefix</code> essentially hard-codes dependencies into the wrapper.
They cannot be overridden without rebuilding the package.
</p>
</div>
</div>
<p>If dependencies should be resolved at runtime, use <code>--suffix</code> to append fallback values to <code>PATH</code>.</p>
<p>There’s many more kinds of arguments, they are documented in <code>nixpkgs/pkgs/build-support/setup-hooks/make-wrapper.sh</code> for the <code>makeWrapper</code> implementation and in <code>nixpkgs/pkgs/build-support/setup-hooks/make-binary-wrapper/make-binary-wrapper.sh</code> for the <code>makeBinaryWrapper</code> implementation.</p>
...
```
The actual `</main>` and `</section>` tags are at the correct place later, but those are ignored by the browser, since it considers them closed already because of the `</div>` tags.

The original markdown for that section looks like this, so I don't know if it's because of the length of the file or because it misinterpreted the `:::{note}` block or what triggered the bug.
```markdown

Use `--prefix` to explicitly set dependencies in `PATH`.

:::{note}
`--prefix` essentially hard-codes dependencies into the wrapper.
They cannot be overridden without rebuilding the package.
:::

If dependencies should be resolved at runtime, use `--suffix` to append fallback values to `PATH`.
```

**Comment by anka-213** [comment]
Searching through the page (and all the docs in the nixpkgs repo), it seems like all other `:::{note}` blocks has a space between, so it's `::: {note}`, so maybe that has something to do with it?

**Comment by ryantm** [comment]
should be resolved by https://github.com/NixOS/nixpkgs/pull/200089

**Comment by ryantm** [comment]
Thank you for looking into this. It is now resolved https://ryantm.github.io/nixpkgs/stdenv/stdenv/#chap-stdenv
