### ISSUE TITLE
Problem building the docs

### ISSUE THREAD

**Issue by henrik-ch** [ryantm/mmdoc#33]
I tried following the instructions on: https://ryantm.github.io/mmdoc/contributing/#contributing

the nix build command worked as far as I can see. The shell commands to build and continuously build didn't work - details below.

`❯ pwd`
`/home/i97henka/github/ryantm-mmdoc`
`❯ ls`
`LICENSE  README.md  contrib  doc  flake.lock  flake.nix  meson.build  pkgs  result  src  test`
`❯ nix build`
`❯ nix shell -c doc-build`
`error: unable to execute 'doc-build': No such file or directory`
`❯ nix shell -c doc-watch`
`error: unable to execute 'doc-watch': No such file or directory`

I haven't got much experience with nix or nix flakes, but I believe my machine is working as it should in terms of nix in general.

**Comment by ryantm** [comment]
Hi, glad to see your interest in this! Sorry for the long reply time.

Try

```
nix develop --command "doc-watch"
```

instead.

**Comment by ryantm** [comment]
Addressed in https://github.com/ryantm/mmdoc/commit/9c320899101f47023fc2006ae08b8a7b3889efb9

**Comment by henrik-ch** [comment]
Tested the command and it works well - when I navigate to localhost:8000 I get this menu structure - and under there the different types of the documentation generation can be accessed.

![image](https://github.com/ryantm/mmdoc/assets/569510/880777a3-4779-4997-8ade-d947c823cbac)

**Comment by ryantm** [comment]
Looks as expected!
