### ISSUE TITLE
Problem with nix fmt

### ISSUE THREAD

**Issue by henrik-ch** [ryantm/mmdoc#41]
Thank you for the update on the contributing page.

One thing that I tried out afterwards didn't work out for me:
`nix fmt`

when running the command I get the result:
```
$ nix fmt
Formatting C code...
Formatting Nix code...
/nix/store/54cjzi4jnky4hcikh2nrlxb9anz3ba7g-fmt/bin/fmt: 4: alejandra: not found
```

when I navigate into the nix store to inspect that file I get:
```
$ cat /nix/store/54cjzi4jnky4hcikh2nrlxb9anz3ba7g-fmt/bin/fmt
echo "Formatting C code..."
find src -iname *.h -o -iname *.c | xargs /nix/store/k25gw7i9z49clsn08s8yk5xjsvh39pf5-clang-tools-14.0.6/bin/clang-format -i
echo "Formatting Nix code..."
alejandra -q .
```

so I think the alejandra utility is missing for some reason, but I am not sure how to modify the flake to get it included?

I looked at the flake (apologies, I am very new to flakes in particular and also nix in general) and found this line:
https://github.com/ryantm/mmdoc/blob/main/flake.nix#L18 
but I am not sure what that means and how it relates to my issue.

**Comment by ryantm** [comment]
https://github.com/ryantm/mmdoc/blob/61758c84f9b8e22dcc8868568360a7fe48b67280/pkgs/fmt.nix#L10

Needs to be changed to reference the Alejandra package. Currently it is referring to the one on the user's path. oops!

**Comment by ryantm** [comment]
Fixed in https://github.com/ryantm/mmdoc/commit/ddcb14b155c02abad1a0dc15993905d577f3c0d8
