### ISSUE TITLE
Issue and trying to understand np-build

### ISSUE THREAD

**Issue by henrik-ch** [ryantm/mmdoc#43]
I am trying to familiarize myself with flakes & nix by looking at your mmdoc project.

I am trying out the following:

```
$ nix develop
(nix:mmdoc-env) bash-5.2$ np-build
error: flake 'git+file:///home/i97henka/github/hkf-mmdoc' does not provide attribute 'packages.x86_64-linux.nixpkgs-manual', 'legacyPackages.x86_64-linux.nixpkgs-manual' or 'nixpkgs-manual'
(nix:mmdoc-env) bash-5.2$
```

and the result I expected is that the nixpkgs manual would build and be symlinked in the results folder.

I found this part of the code, which seems to define the np-build script.
https://github.com/ryantm/mmdoc/blob/main/pkgs/devShell.nix#L39

but I am not quite sure how it is supposed to work.

**Comment by proofconstruction** [comment]
This error message means `nixpkgs-manual` is not in the `packages` output of the flake; in this case, the `nixpkgs-manual` attribute should refer to the `minman` branch of @ryantm's nixpkgs fork [here](https://github.com/ryantm/nixpkgs/tree/minman).

To get this working, you'll need to change the nixpkgs in the `flake.nix` to `inputs.nixpkgs.url = "github:ryantm/nixpkgs/minman";`, and then make these additions to `pkgs/default.nix`:

```diff
{ nixpkgs
, system
, self
,
}:
let
  pkgs = nixpkgs.legacyPackages.${system};
+ nixpkgs-for-manual = pkgs.fetchFromGitHub {
+   owner = "ryantm";
+   repo = "nixpkgs";
+   rev = "99bc88dcdbdd8f375fd3cd7395eafe55d9857283";
+   sha256 = "08q5y5j2qpxk5gpjyhbz10ghyzicbdqibfpfnxgxq8fz649r1i7w";
+ };
in
rec {
  default = mmdoc;
  mmdoc = pkgs.callPackage ./mmdoc.nix { inherit self; };
  mmdoc-docs = pkgs.callPackage ./mmdoc-docs.nix { inherit mmdoc; };
  devShell = pkgs.callPackage ./devShell.nix { };
  fmt = pkgs.callPackage ./fmt.nix { };
+ nixpkgs-manual = pkgs.callPackage ./nixpkgs-manual.nix { inherit nixpkgs-for-manual mmdoc; };
}
```

**Comment by henrik-ch** [comment]
Thank you @proofconstruction - this indeed works. Do you think that this is something that would make sense to PR?

**Comment by proofconstruction** [comment]
> Thank you @proofconstruction - this indeed works. Do you think that this is something that would make sense to PR?

Go for it!
